-- 2058_seed_venues_from_add_catch.sql
-- Seed venues from existing Add Catch fishery options (see src/lib/freshwater-data.ts and docs/VENUE-PAGES-DESIGN.md)

SET search_path = public, extensions;

INSERT INTO public.venues (slug, name, location, description, is_published, created_at, updated_at)
VALUES
  ('anglers-paradise-devon', 'Anglers Paradise, Devon', 'Devon, UK', 'Imported from Add Catch venue options.', true, now(), now()),
  ('avington-trout-fishery-hampshire', 'Avington Trout Fishery, Hampshire', 'Hampshire, UK', 'Imported from Add Catch venue options.', true, now(), now()),
  ('badshot-lea-big-pond-surrey', 'Badshot Lea Big Pond, Surrey', 'Surrey, UK', 'Imported from Add Catch venue options.', true, now(), now()),
  ('barston-lakes-west-midlands', 'Barston Lakes, West Midlands', 'West Midlands, UK', 'Imported from Add Catch venue options.', true, now(), now()),
  ('bewl-water-kent', 'Bewl Water, Kent', 'Kent, UK', 'Imported from Add Catch venue options.', true, now(), now()),
  ('blagdon-lake-somerset', 'Blagdon Lake, Somerset', 'Somerset, UK', 'Imported from Add Catch venue options.', true, now(), now()),
  ('bluebell-lakes-northamptonshire', 'Bluebell Lakes, Northamptonshire', 'Northamptonshire, UK', 'Imported from Add Catch venue options.', true, now(), now()),
  ('boddington-reservoir-northamptonshire', 'Boddington Reservoir, Northamptonshire', 'Northamptonshire, UK', 'Imported from Add Catch venue options.', true, now(), now()),
  ('bratton-water-devon', 'Bratton Water, Devon', 'Devon, UK', 'Imported from Add Catch venue options.', true, now(), now()),
  ('broadwater-lake-surrey', 'Broadwater Lake, Surrey', 'Surrey, UK', 'Imported from Add Catch venue options.', true, now(), now()),
  ('brotherswood-lakes-west-sussex', 'Brotherswood Lakes, West Sussex', 'West Sussex, UK', 'Imported from Add Catch venue options.', true, now(), now()),
  ('burton-springs-somerset', 'Burton Springs, Somerset', 'Somerset, UK', 'Imported from Add Catch venue options.', true, now(), now()),
  ('bury-hill-fisheries-surrey', 'Bury Hill Fisheries, Surrey', 'Surrey, UK', 'Imported from Add Catch venue options.', true, now(), now()),
  ('caldicot-castle-lake-monmouthshire', 'Caldicot Castle Lake, Monmouthshire', 'Monmouthshire, UK', 'Imported from Add Catch venue options.', true, now(), now()),
  ('carsington-water-derbyshire', 'Carsington Water, Derbyshire', 'Derbyshire, UK', 'Imported from Add Catch venue options.', true, now(), now()),
  ('chew-valley-lake-somerset', 'Chew Valley Lake, Somerset', 'Somerset, UK', 'Imported from Add Catch venue options.', true, now(), now()),
  ('chigboro-fisheries-essex', 'Chigboro Fisheries, Essex', 'Essex, UK', 'Imported from Add Catch venue options.', true, now(), now()),
  ('cholmondeley-castle-lakes-cheshire', 'Cholmondeley Castle Lakes, Cheshire', 'Cheshire, UK', 'Imported from Add Catch venue options.', true, now(), now()),
  ('church-lake-chapel-baits-kent', 'Church Lake (Chapel Baits), Kent', 'Kent, UK', 'Imported from Add Catch venue options.', true, now(), now()),
  ('clattercote-reservoir-oxfordshire', 'Clattercote Reservoir, Oxfordshire', 'Oxfordshire, UK', 'Imported from Add Catch venue options.', true, now(), now()),
  ('clywedog-reservoir-powys', 'Clywedog Reservoir, Powys', 'Powys, UK', 'Imported from Add Catch venue options.', true, now(), now()),
  ('coed-ty-mawr-fishery-wrexham', 'Coed Ty Mawr Fishery, Wrexham', 'Wrexham, UK', 'Imported from Add Catch venue options.', true, now(), now()),
  ('colwick-country-park-nottinghamshire', 'Colwick Country Park, Nottinghamshire', 'Nottinghamshire, UK', 'Imported from Add Catch venue options.', true, now(), now()),
  ('colwick-park-trout-lake-nottinghamshire', 'Colwick Park Trout Lake, Nottinghamshire', 'Nottinghamshire, UK', 'Imported from Add Catch venue options.', true, now(), now()),
  ('cotswold-water-park-gloucestershire', 'Cotswold Water Park, Gloucestershire', 'Gloucestershire, UK', 'Imported from Add Catch venue options.', true, now(), now()),
  ('creslow-pools-buckinghamshire', 'Creslow Pools, Buckinghamshire', 'Buckinghamshire, UK', 'Imported from Add Catch venue options.', true, now(), now()),
  ('docklow-pools-herefordshire', 'Docklow Pools, Herefordshire', 'Herefordshire, UK', 'Imported from Add Catch venue options.', true, now(), now()),
  ('drayton-reservoir-northamptonshire', 'Drayton Reservoir, Northamptonshire', 'Northamptonshire, UK', 'Imported from Add Catch venue options.', true, now(), now()),
  ('earith-lakes-cambridgeshire', 'Earith Lakes, Cambridgeshire', 'Cambridgeshire, UK', 'Imported from Add Catch venue options.', true, now(), now()),
  ('eden-springs-trout-fishery-cumbria', 'Eden Springs Trout Fishery, Cumbria', 'Cumbria, UK', 'Imported from Add Catch venue options.', true, now(), now()),
  ('elinor-trout-fishery-northamptonshire', 'Elinor Trout Fishery, Northamptonshire', 'Northamptonshire, UK', 'Imported from Add Catch venue options.', true, now(), now()),
  ('elphicks-fisheries-kent', 'Elphicks Fisheries, Kent', 'Kent, UK', 'Imported from Add Catch venue options.', true, now(), now()),
  ('esthwaite-water-trout-fishery-cumbria', 'Esthwaite Water Trout Fishery, Cumbria', 'Cumbria, UK', 'Imported from Add Catch venue options.', true, now(), now()),
  ('eyebrook-reservoir-leicestershire', 'Eyebrook Reservoir, Leicestershire', 'Leicestershire, UK', 'Imported from Add Catch venue options.', true, now(), now()),
  ('farmoor-reservoir-oxfordshire', 'Farmoor Reservoir, Oxfordshire', 'Oxfordshire, UK', 'Imported from Add Catch venue options.', true, now(), now()),
  ('farnham-flint-lakes-surrey', 'Farnham Flint Lakes, Surrey', 'Surrey, UK', 'Imported from Add Catch venue options.', true, now(), now()),
  ('farlows-lake-buckinghamshire', 'Farlows Lake, Buckinghamshire', 'Buckinghamshire, UK', 'Imported from Add Catch venue options.', true, now(), now()),
  ('forest-lane-fisheries-cheshire', 'Forest Lane Fisheries, Cheshire', 'Cheshire, UK', 'Imported from Add Catch venue options.', true, now(), now()),
  ('frensham-great-pond-surrey', 'Frensham Great Pond, Surrey', 'Surrey, UK', 'Imported from Add Catch venue options.', true, now(), now()),
  ('frensham-small-pond-surrey', 'Frensham Small Pond, Surrey', 'Surrey, UK', 'Imported from Add Catch venue options.', true, now(), now()),
  ('furnace-mill-fisheries-worcestershire', 'Furnace Mill Fisheries, Worcestershire', 'Worcestershire, UK', 'Imported from Add Catch venue options.', true, now(), now()),
  ('gailey-reservoir-staffordshire', 'Gailey Reservoir, Staffordshire', 'Staffordshire, UK', 'Imported from Add Catch venue options.', true, now(), now()),
  ('garnffrwd-fishery-carmarthenshire', 'Garnffrwd Fishery, Carmarthenshire', 'Carmarthenshire, UK', 'Imported from Add Catch venue options.', true, now(), now()),
  ('gingerbread-lake-bedfordshire', 'Gingerbread Lake, Bedfordshire', 'Bedfordshire, UK', 'Imported from Add Catch venue options.', true, now(), now()),
  ('gold-valley-lakes-hampshire', 'Gold Valley Lakes, Hampshire', 'Hampshire, UK', 'Imported from Add Catch venue options.', true, now(), now()),
  ('grafham-water-cambridgeshire', 'Grafham Water, Cambridgeshire', 'Cambridgeshire, UK', 'Imported from Add Catch venue options.', true, now(), now()),
  ('grebe-lake-bedfordshire', 'Grebe Lake, Bedfordshire', 'Bedfordshire, UK', 'Imported from Add Catch venue options.', true, now(), now()),
  ('hanningfield-reservoir-essex', 'Hanningfield Reservoir, Essex', 'Essex, UK', 'Imported from Add Catch venue options.', true, now(), now()),
  ('hayfield-lakes-south-yorkshire', 'Hayfield Lakes, South Yorkshire', 'South Yorkshire, UK', 'Imported from Add Catch venue options.', true, now(), now()),
  ('holgan-farm-pembrokeshire', 'Holgan Farm, Pembrokeshire', 'Pembrokeshire, UK', 'Imported from Add Catch venue options.', true, now(), now()),
  ('horseshoe-lake-gloucestershire', 'Horseshoe Lake, Gloucestershire', 'Gloucestershire, UK', 'Imported from Add Catch venue options.', true, now(), now()),
  ('kilnsey-park-estate-north-yorkshire', 'Kilnsey Park Estate, North Yorkshire', 'North Yorkshire, UK', 'Imported from Add Catch venue options.', true, now(), now()),
  ('kingfisher-trout-lake-devon', 'Kingfisher Trout Lake, Devon', 'Devon, UK', 'Imported from Add Catch venue options.', true, now(), now()),
  ('kingsbury-water-park-warwickshire', 'Kingsbury Water Park, Warwickshire', 'Warwickshire, UK', 'Imported from Add Catch venue options.', true, now(), now()),
  ('ladybower-fisheries-derbyshire', 'Ladybower Fisheries, Derbyshire', 'Derbyshire, UK', 'Imported from Add Catch venue options.', true, now(), now()),
  ('lakelands-trout-fishery-cheshire', 'Lakelands Trout Fishery, Cheshire', 'Cheshire, UK', 'Imported from Add Catch venue options.', true, now(), now()),
  ('linear-fisheries-brasenose-1-oxfordshire', 'Linear Fisheries - Brasenose 1, Oxfordshire', 'Oxfordshire, UK', 'Imported from Add Catch venue options.', true, now(), now()),
  ('linear-fisheries-brasenose-2-oxfordshire', 'Linear Fisheries - Brasenose 2, Oxfordshire', 'Oxfordshire, UK', 'Imported from Add Catch venue options.', true, now(), now()),
  ('linear-fisheries-hardwick-smiths-oxfordshire', 'Linear Fisheries - Hardwick & Smiths, Oxfordshire', 'Oxfordshire, UK', 'Imported from Add Catch venue options.', true, now(), now()),
  ('linear-fisheries-hunts-corner-oxfordshire', 'Linear Fisheries - Hunts Corner, Oxfordshire', 'Oxfordshire, UK', 'Imported from Add Catch venue options.', true, now(), now()),
  ('linear-fisheries-oxlease-lake-oxfordshire', 'Linear Fisheries - Oxlease Lake, Oxfordshire', 'Oxfordshire, UK', 'Imported from Add Catch venue options.', true, now(), now()),
  ('linear-fisheries-st-johns-lake-oxfordshire', 'Linear Fisheries - St. Johns Lake, Oxfordshire', 'Oxfordshire, UK', 'Imported from Add Catch venue options.', true, now(), now()),
  ('lockwood-beck-reservoir-north-yorkshire', 'Lockwood Beck Reservoir, North Yorkshire', 'North Yorkshire, UK', 'Imported from Add Catch venue options.', true, now(), now()),
  ('llyn-brenig-denbighshire', 'Llyn Brenig, Denbighshire', 'Denbighshire, Wales', 'Imported from Add Catch venue options.', true, now(), now()),
  ('llyn-clywedog-powys', 'Llyn Clywedog, Powys', 'Powys, Wales', 'Imported from Add Catch venue options.', true, now(), now()),
  ('llyn-trawsfynydd-gwynedd', 'Llyn Trawsfynydd, Gwynedd', 'Gwynedd, Wales', 'Imported from Add Catch venue options.', true, now(), now()),
  ('lodge-farm-fisheries-northamptonshire', 'Lodge Farm Fisheries, Northamptonshire', 'Northamptonshire, UK', 'Imported from Add Catch venue options.', true, now(), now()),
  ('loch-leven-perth-and-kinross', 'Loch Leven, Perth and Kinross', 'Perth and Kinross, Scotland', 'Imported from Add Catch venue options.', true, now(), now()),
  ('loch-awe-argyll-and-bute', 'Loch Awe, Argyll and Bute', 'Argyll and Bute, Scotland', 'Imported from Add Catch venue options.', true, now(), now()),
  ('loch-lomond-west-dunbartonshire', 'Loch Lomond, West Dunbartonshire', 'West Dunbartonshire, Scotland', 'Imported from Add Catch venue options.', true, now(), now()),
  ('manor-farm-lakes-bedfordshire', 'Manor Farm Lakes, Bedfordshire', 'Bedfordshire, UK', 'Imported from Add Catch venue options.', true, now(), now()),
  ('meadowlands-fishery-warwickshire', 'Meadowlands Fishery, Warwickshire', 'Warwickshire, UK', 'Imported from Add Catch venue options.', true, now(), now()),
  ('milton-pools-fishery-oxfordshire', 'Milton Pools Fishery, Oxfordshire', 'Oxfordshire, UK', 'Imported from Add Catch venue options.', true, now(), now()),
  ('monk-lakes-kent', 'Monk Lakes, Kent', 'Kent, UK', 'Imported from Add Catch venue options.', true, now(), now()),
  ('old-bury-hill-lake-surrey', 'Old Bury Hill Lake, Surrey', 'Surrey, UK', 'Imported from Add Catch venue options.', true, now(), now()),
  ('partridge-lakes-fishery-cheshire', 'Partridge Lakes Fishery, Cheshire', 'Cheshire, UK', 'Imported from Add Catch venue options.', true, now(), now()),
  ('portsmouth-watersports-centre-lake-hampshire', 'Portsmouth Watersports Centre Lake, Hampshire', 'Hampshire, UK', 'Imported from Add Catch venue options.', true, now(), now()),
  ('redmire-pool-herefordshire', 'Redmire Pool, Herefordshire', 'Herefordshire, UK', 'Imported from Add Catch venue options.', true, now(), now()),
  ('ringstead-grange-northamptonshire', 'Ringstead Grange, Northamptonshire', 'Northamptonshire, UK', 'Imported from Add Catch venue options.', true, now(), now()),
  ('rookery-waters-cambridgeshire', 'Rookery Waters, Cambridgeshire', 'Cambridgeshire, UK', 'Imported from Add Catch venue options.', true, now(), now()),
  ('rutland-water-rutland', 'Rutland Water, Rutland', 'Rutland, UK', 'Imported from Add Catch venue options.', true, now(), now()),
  ('staunton-harold-reservoir-leicestershire', 'Staunton Harold Reservoir, Leicestershire', 'Leicestershire, UK', 'Imported from Add Catch venue options.', true, now(), now()),
  ('stocks-reservoir-lancashire', 'Stocks Reservoir, Lancashire', 'Lancashire, UK', 'Imported from Add Catch venue options.', true, now(), now()),
  ('stour-valley-lakes-dorset', 'Stour Valley Lakes, Dorset', 'Dorset, UK', 'Imported from Add Catch venue options.', true, now(), now()),
  ('sutton-lake-shropshire', 'Sutton Lake, Shropshire', 'Shropshire, UK', 'Imported from Add Catch venue options.', true, now(), now()),
  ('thornham-fishery-norfolk', 'Thornham Fishery, Norfolk', 'Norfolk, UK', 'Imported from Add Catch venue options.', true, now(), now()),
  ('todber-manor-fisheries-dorset', 'Todber Manor Fisheries, Dorset', 'Dorset, UK', 'Imported from Add Catch venue options.', true, now(), now()),
  ('upper-tamar-lake-cornwall', 'Upper Tamar Lake, Cornwall', 'Cornwall, UK', 'Imported from Add Catch venue options.', true, now(), now()),
  ('walthamstow-reservoirs-london', 'Walthamstow Reservoirs, London', 'London, UK', 'Imported from Add Catch venue options.', true, now(), now()),
  ('watermark-lakes-gloucestershire', 'Watermark Lakes, Gloucestershire', 'Gloucestershire, UK', 'Imported from Add Catch venue options.', true, now(), now()),
  ('weston-pools-shropshire', 'Weston Pools, Shropshire', 'Shropshire, UK', 'Imported from Add Catch venue options.', true, now(), now()),
  ('willow-park-fishery-hampshire', 'Willow Park Fishery, Hampshire', 'Hampshire, UK', 'Imported from Add Catch venue options.', true, now(), now()),
  ('willowgate-fishery-perthshire', 'Willowgate Fishery, Perthshire', 'Perthshire, Scotland', 'Imported from Add Catch venue options.', true, now(), now()),
  ('wingham-fisheries-kent', 'Wingham Fisheries, Kent', 'Kent, UK', 'Imported from Add Catch venue options.', true, now(), now()),
  ('wraysbury-1-south-lake-berkshire', 'Wraysbury 1 South Lake, Berkshire', 'Berkshire, UK', 'Imported from Add Catch venue options.', true, now(), now()),
  ('wraysbury-no-1-berkshire', 'Wraysbury No. 1, Berkshire', 'Berkshire, UK', 'Imported from Add Catch venue options.', true, now(), now())
ON CONFLICT (slug) DO NOTHING;
